version: "3.8"
services:
  redis:
    image: redis:alpine
    restart: always
    platform: linux/arm64/v8
    command: redis-server --port 6379
    container_name: redis-server
    hostname: redis-server
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
